site_name: Manny
site_url: https://Manny.github.io
nav:
    - Text Substitution with SED: index.md
theme:
    name: material
    features:
      search.suggest
      search.highlight
      content.tabs.link
